AllCops:
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*

inherit_gem:
  lintsyle:
    - rubocop.yml

inherit_mode:
  merge:
    - Exclude
    - Include
